include mk/common.mk
include mk/security-sources.mk
include mk/agent-sources.mk
include mk/backend-agent-runtime.mk

include mk/recording-sources.mk
include mk/metadata-sources.mk
include mk/genre-browser.mk
include mk/global-search.mk
include mk/action-job-sources.mk
include mk/rest-sources.mk
include mk/vdr-sources.mk
include mk/http-sources.mk
include mk/runtime-sources.mk
include mk/daemon-sources.mk
include mk/tmdb-series-artwork.mk
include mk/manual-recording-metadata.mk
include mk/install.mk
include mk/public-origin.mk
include mk/live-remote.mk
include mk/test-inventory-exceptions.mk
include mk/local-test-groups.mk
include mk/object-cache.mk
include mk/recordings2.mk



include mk/smoke-targets.mk
include mk/phase62-runtime-acceptance.mk
include mk/phase62-outcome-runtime-acceptance.mk
include mk/phase62-idle-runtime-acceptance.mk
include mk/phase62-retention-runtime-acceptance.mk
include mk/phase63-runtime-acceptance.mk
include mk/agent-tests.mk
include mk/phase63-local-provider-tests.mk
include mk/phase64-timer-intent-tests.mk
include mk/phase64-native-timer-readback-expectation-tests.mk
include mk/phase64-native-timer-present-readback-verification-tests.mk
include mk/phase64-native-timer-inventory-evidence-tests.mk
include mk/phase64-restfulapi-native-timer-inventory-reader-tests.mk
include mk/phase64-native-timer-binding-absence-application-tests.mk
include mk/phase64-native-timer-absence-readback-expectation-tests.mk
include mk/phase64-native-timer-absence-readback-verification-tests.mk
include mk/recording-native-metadata-tests.mk
include mk/recording-action-tests.mk
include mk/recording-metadata-tests.mk
include mk/metadata-tests.mk
include mk/application-tests.mk
include mk/domain-tests.mk
include mk/search-timer-api-tests.mk
include mk/search-timer-workflow-tests.mk
include mk/runtime-api-tests.mk
include mk/maintenance-tests.mk
include mk/epg-artwork-tests.mk
include mk/epg-metadata-tests.mk
