include mk/common.mk
include mk/security-sources.mk
include mk/agent-sources.mk
include mk/backend-agent-runtime.mk

include mk/recording-sources.mk
include mk/metadata-sources.mk
include mk/genre-browser.mk
include mk/global-search.mk
include mk/action-job-sources.mk
include mk/rest-sources.mk
include mk/vdr-sources.mk
include mk/http-sources.mk
include mk/runtime-sources.mk
include mk/daemon-sources.mk
include mk/tmdb-series-artwork.mk
include mk/manual-recording-metadata.mk
include mk/install.mk
include mk/public-origin.mk
include mk/live-remote.mk
include mk/test-inventory-exceptions.mk
include mk/local-test-groups.mk
include mk/object-cache.mk
include mk/recordings2.mk



include mk/smoke-targets.mk
include mk/phase62-runtime-acceptance.mk
include mk/phase62-outcome-runtime-acceptance.mk
include mk/phase62-idle-runtime-acceptance.mk
include mk/phase62-retention-runtime-acceptance.mk
include mk/phase63-runtime-acceptance.mk
include mk/agent-tests.mk
include mk/phase64-backend-agent-command-reservation-tests.mk
include mk/phase64-native-timer-create-agent-contract-tests.mk
include mk/phase64-native-timer-create-reservation-tests.mk
include mk/phase64-native-timer-create-dispatch-state-tests.mk
include mk/phase64-native-timer-create-outcome-completion-tests.mk
include mk/phase64-native-timer-create-delivery-tests.mk
include mk/phase64-native-timer-create-activation-tests.mk
include mk/phase64-native-timer-create-local-state-tests.mk
include mk/phase64-native-timer-create-executor-tests.mk
include mk/phase64-suitebridge-native-timer-create-transport-tests.mk
include mk/phase64-suitebridge-native-timer-create-command-service-tests.mk
include mk/phase64-suitebridge-native-timer-create-real-mutation-tests.mk
include mk/phase64-suitebridge-native-timer-command-path-wiring-tests.mk
include mk/phase63-local-provider-tests.mk
include mk/phase64-timer-intent-tests.mk
include mk/phase64-timer-intent-application-tests.mk
include mk/phase64-timer-assignment-fulfillment-tests.mk
include mk/phase64-native-timer-specification-tests.mk
include mk/phase64-vdr-timer-managed-correlation-tests.mk
include mk/phase64-vdr-managed-timer-create-request-tests.mk
include mk/phase64-native-timer-readback-expectation-tests.mk
include mk/phase64-native-timer-create-readback-expectation-tests.mk
include mk/phase64-native-timer-create-readback-evidence-tests.mk
include mk/phase64-vdr-managed-timer-create-readback-evidence-tests.mk
include mk/phase64-native-timer-create-readback-verification-tests.mk
include mk/phase64-native-timer-present-readback-verification-tests.mk
include mk/phase64-native-timer-inventory-evidence-tests.mk
include mk/phase64-restfulapi-native-timer-inventory-reader-tests.mk
include mk/phase64-native-timer-binding-absence-application-tests.mk
include mk/phase64-native-timer-absence-readback-expectation-tests.mk
include mk/phase64-native-timer-absence-readback-verification-tests.mk
include mk/phase64-mutation-operation-repository-tests.mk
include mk/phase64-native-timer-create-operation-preparation-tests.mk
include mk/phase64-native-timer-modify-operation-tests.mk
include mk/phase64-native-timer-modify-dispatch-tests.mk
include mk/phase64-managed-timer-fulfillment-acceptance.mk
include mk/phase64-timer-reassignment-failover-tests.mk
include mk/phase64-reassignment-failover-acceptance.mk
include mk/phase64-native-timer-delete-operation-completion-tests.mk
include mk/phase64-native-timer-delete-operation-preparation-tests.mk
include mk/phase64-native-timer-delete-dispatch-tests.mk
include mk/phase64-native-timer-delete-agent-contract-tests.mk
include mk/phase64-native-timer-delete-assignment-tests.mk
include mk/phase64-native-timer-delete-delivery-tests.mk
include mk/phase64-native-timer-delete-local-starting-tests.mk
include mk/phase64-command-state-extension-tests.mk
include mk/phase64-command-state-v3-extension-tests.mk
include mk/phase64-timer-delete-local-state-lifecycle-tests.mk
include mk/phase64-timer-delete-fresh-durable-starting-tests.mk
include mk/phase64-timer-delete-fenced-executor-tests.mk
include mk/phase64-timer-delete-durable-executor-outcome-tests.mk
include mk/phase64-suitebridge-native-timer-delete-disabled-transport-tests.mk
include mk/phase64-suitebridge-native-timer-delete-replay-ledger-callback-tests.mk
include mk/phase64-suitebridge-native-timer-delete-real-mutation-tests.mk
include mk/recording-native-metadata-tests.mk
include mk/recording-action-tests.mk
include mk/recording-metadata-tests.mk
include mk/metadata-tests.mk
include mk/application-tests.mk
include mk/domain-tests.mk
include mk/search-timer-api-tests.mk
include mk/search-timer-workflow-tests.mk
include mk/runtime-api-tests.mk
include mk/maintenance-tests.mk
include mk/epg-artwork-tests.mk
include mk/epg-metadata-tests.mk
