DAEMON_SRC := \
        core/daemon/src/RuntimeConfig.cpp \
        core/recordings/src/JobRepository.cpp \
        core/recordings/src/JobDashboardService.cpp \
        core/recordings/src/RecordingRepository.cpp \
        core/recordings/src/MetadataRepository.cpp \
        core/recordings/src/RecordingDashboardService.cpp \
        core/recordings/src/DashboardFacade.cpp \
        core/recordings/src/DashboardJsonSerializer.cpp \
        api/rest/src/DashboardController.cpp \
        api/rest/src/JobsController.cpp \
        api/rest/src/RecordingsController.cpp \
        api/rest/src/MetadataController.cpp \
        api/rest/src/PersonController.cpp \
        api/rest/src/RecordingPersonSearchController.cpp \
        core/vdr/src/RecordingPersonSearchService.cpp \
        core/vdr/src/RecordingPersonSearchResultJsonSerializer.cpp \
        core/vdr/src/PersonQueryMatcher.cpp \
        core/vdr/src/PersonQueryResultJsonSerializer.cpp \
        core/vdr/src/PersonResolutionJsonSerializer.cpp \
        core/vdr/src/PersonSearchService.cpp \
        api/rest/src/VdrController.cpp \
        api/rest/src/VdrRecordingQueryController.cpp \
        api/rest/src/EpgController.cpp \
        api/rest/src/EpgSearchNativeFuzzyStaleProbeAdministrationController.cpp \
        api/rest/src/EpgSearchNativeFuzzyOperatorRefreshController.cpp \
        api/rest/src/SearchTimerController.cpp \
        api/rest/src/SearchTimerDiscoveryController.cpp \
        core/vdr/src/SearchTimerResultJsonSerializer.cpp \
        core/vdr/src/SearchTimerService.cpp \
        core/vdr/src/RestfulApiSearchTimerMapper.cpp \
        core/vdr/src/RestfulApiSearchTimerAdapter.cpp \
        core/vdr/src/EpgSearchNativeFuzzyCapabilityRepository.cpp \
        core/vdr/src/EpgSearchNativeFuzzyCapabilityFreshnessPolicy.cpp \
        core/vdr/src/EpgSearchNativeFuzzyStartupRestoreService.cpp \
        core/vdr/src/EpgSearchNativeFuzzyStartupRestoreDiagnostics.cpp \
        core/vdr/src/EpgSearchNativeFuzzyStaleProbeAdministrationService.cpp \
        core/vdr/src/EpgSearchNativeFuzzyOperatorRefreshService.cpp \
        api/rest/src/RestQueryParameters.cpp \
        api/rest/src/BackendRegistryController.cpp \
        api/rest/src/RuntimeDiagnosticsController.cpp \
        api/rest/src/SnapshotChangeFeedController.cpp \
        api/rest/src/LiveTransportController.cpp \
        api/rest/src/CapabilityController.cpp \
        api/rest/src/RecordingActionValidationController.cpp \
        api/rest/src/RecordingActionExecutionController.cpp \
        api/rest/src/VdrTimerActionController.cpp \
        core/recordings/src/RecordingActionUtils.cpp \
        core/recordings/src/RecordingActionValidationResultJsonSerializer.cpp \
        core/recordings/src/RecordingActionExecutionResultJsonSerializer.cpp \
        core/recordings/src/RecordingActionSafetyResultJsonSerializer.cpp \
        core/recordings/src/RecordingActionValidationService.cpp \
        api/rest/src/RecordingActionValidationRequestParser.cpp \
        core/vdr/src/VdrTimerActionService.cpp \
        core/vdr/src/VdrTimerActionExecutionService.cpp \
        core/vdr/src/VdrTimerActionResultJsonSerializer.cpp \
        core/vdr/src/RestfulApiVdrTimerActionExecutor.cpp \
        core/vdr/src/RestfulApiVdrTimerActionExecutorAdapter.cpp \
        api/rest/src/VdrTimerActionRequestParser.cpp \
        api/rest/src/ApiRouter.cpp \
        core/http/src/BasicHttpClient.cpp \
        core/http/src/SimpleHttpListener.cpp \
        core/http/src/TestHttpServer.cpp \
        core/daemon/src/DaemonRuntime.cpp \
        core/daemon/src/DaemonApp.cpp \
        api/rest/src/SearchTimerCreateRequestParser.cpp \
        api/rest/src/SearchTimerUpdateRequestParser.cpp \
        api/rest/src/SearchTimerDeleteRequestParser.cpp \
        api/rest/src/SearchTimerWorkflowValidationRequestParser.cpp \
