DAEMON_SRC := \
        core/daemon/src/RuntimeConfig.cpp \
        core/recordings/src/JobRepository.cpp \
        core/recordings/src/JobDashboardService.cpp \
        core/recordings/src/RecordingRepository.cpp \
        core/recordings/src/MetadataRepository.cpp \
        core/recordings/src/RecordingDashboardService.cpp \
        core/recordings/src/DashboardFacade.cpp \
        core/recordings/src/DashboardJsonSerializer.cpp \
        api/rest/src/DashboardController.cpp \
        api/rest/src/JobsController.cpp \
        api/rest/src/RecordingsController.cpp \
        api/rest/src/MetadataController.cpp \
        api/rest/src/PersonController.cpp \
        api/rest/src/RecordingPersonSearchController.cpp \
        core/vdr/src/RecordingPersonSearchService.cpp \
        core/vdr/src/RecordingPersonSearchResultJsonSerializer.cpp \
        core/vdr/src/PersonQueryMatcher.cpp \
        core/vdr/src/PersonQueryResultJsonSerializer.cpp \
        core/vdr/src/PersonResolutionJsonSerializer.cpp \
        core/vdr/src/PersonSearchService.cpp \
        api/rest/src/VdrController.cpp \
        api/rest/src/VdrRecordingQueryController.cpp \
        api/rest/src/VdrRecordingFolderController.cpp \
        api/rest/src/EpgController.cpp \
        api/rest/src/EpgCacheController.cpp \
        api/rest/src/EpgArtworkController.cpp \
        api/rest/src/EpgSearchNativeFuzzyStaleProbeAdministrationController.cpp \
        api/rest/src/EpgSearchNativeFuzzyOperatorRefreshController.cpp \
        api/rest/src/SearchTimerController.cpp \
        api/rest/src/SearchTimerDiscoveryController.cpp \
        api/rest/src/SearchTimerAutomationPreviewController.cpp \
        api/rest/src/SearchTimerPreviewEpgCacheRefreshController.cpp \
        api/rest/src/SeriesArtworkSettingsApiRuntime.cpp \
        api/rest/src/ManualRecordingMetadataApiRuntime.cpp \
        api/rest/src/RecordingMediaSessionController.cpp \
        api/rest/src/RecordingMediaSessionRequestParser.cpp \
        $(GENRE_BROWSER_REST_SRC) \
        $(GLOBAL_SEARCH_SRC) \
        $(REST_LIVE_REMOTE_SRC) \
        core/vdr/src/EpgEventRepository.cpp \
        core/vdr/src/VdrRecordingCacheRepository.cpp \
        core/vdr/src/VdrRecordingArtworkService.cpp \
        core/vdr/src/EpgCacheService.cpp \
        core/vdr/src/SearchTimerResultJsonSerializer.cpp \
        core/vdr/src/SearchTimerService.cpp \
        core/vdr/src/RestfulApiSearchTimerMapper.cpp \
        core/vdr/src/RestfulApiSearchTimerAdapter.cpp \
        core/vdr/src/EpgSearchNativeFuzzyCapabilityRepository.cpp \
        core/vdr/src/EpgSearchNativeFuzzyCapabilityFreshnessPolicy.cpp \
        core/vdr/src/EpgSearchNativeFuzzyStartupRestoreService.cpp \
        core/vdr/src/EpgSearchNativeFuzzyStartupRestoreDiagnostics.cpp \
        core/vdr/src/EpgSearchNativeFuzzyStaleProbeAdministrationService.cpp \
        core/vdr/src/EpgSearchNativeFuzzyOperatorRefreshService.cpp \
        api/rest/src/RestQueryParameters.cpp \
        api/rest/src/BackendRegistryController.cpp \
        api/rest/src/RuntimeDiagnosticsController.cpp \
        api/rest/src/SnapshotChangeFeedController.cpp \
        api/rest/src/LiveTransportController.cpp \
        api/rest/src/CapabilityController.cpp \
        api/rest/src/RecordingActionValidationController.cpp \
        api/rest/src/RecordingActionExecutionController.cpp \
        api/rest/src/RecordingActionPreviewController.cpp \
        api/rest/src/VdrTimerActionController.cpp \
        api/rest/src/VdrChannelMoveRequestParser.cpp \
        api/rest/src/VdrChannelMoveController.cpp \
        core/recordings/src/RecordingActionUtils.cpp \
        core/recordings/src/RecordingActionValidationResultJsonSerializer.cpp \
        core/recordings/src/RecordingActionExecutionResultJsonSerializer.cpp \
        core/recordings/src/RecordingActionRequestPreviewResultJsonSerializer.cpp \
        core/recordings/src/RecordingActionSafetyResultJsonSerializer.cpp \
        core/recordings/src/RecordingActionValidationService.cpp \
        api/rest/src/RecordingActionValidationRequestParser.cpp \
        core/vdr/src/VdrTimerActionService.cpp \
        core/vdr/src/VdrTimerActionExecutionService.cpp \
        core/vdr/src/VdrTimerActionResultJsonSerializer.cpp \
        core/vdr/src/RestfulApiVdrTimerActionExecutor.cpp \
        core/vdr/src/RestfulApiVdrTimerActionExecutorAdapter.cpp \
        api/rest/src/VdrTimerActionRequestParser.cpp \
        api/rest/src/ApiRouter.cpp \
        core/http/src/BasicHttpClient.cpp \
        core/http/src/SimpleHttpListener.cpp \
        core/http/src/BrowserSessionCsrfRecoveryService.cpp \
        core/http/src/BrowserSessionHttpService.cpp \
        core/http/src/TestHttpServer.cpp \
        core/http/src/MediaGatewayHttpServer.cpp \
        core/media/src/LocalVdrRecordingSourceResolver.cpp \
        core/media/src/FfprobeRecordingSource.cpp \
        core/media/src/MediaPresentationSelector.cpp \
        core/media/src/MediaTranscodePolicy.cpp \
        core/media/src/FfmpegHlsCommandBuilder.cpp \
        core/media/src/MediaProcessRunner.cpp \
        core/media/src/MediaSessionWorkspace.cpp \
        core/media/src/MediaSessionRepository.cpp \
        core/media/src/MediaRouteLeaseRepository.cpp \
        core/media/src/MediaSessionIssuanceService.cpp \
        core/media/src/MediaAccessGrantAuthenticator.cpp \
        core/media/src/MediaHlsArtifactReader.cpp \
        core/media/src/RecordingMediaSessionRuntime.cpp \
        core/daemon/src/SeriesArtworkBackendSettingsService.cpp \
        core/daemon/src/RecordingArtworkHttpServer.cpp \
        core/daemon/src/RestfulApiEventStreamClient.cpp \
        core/daemon/src/DaemonRuntimeBackendContext.cpp \
        core/daemon/src/DaemonRuntimeInitialization.cpp \
        core/daemon/src/DaemonRuntimePolling.cpp \
        core/daemon/src/DaemonRuntimeEpgCache.cpp \
        core/daemon/src/DaemonRuntimeRecordingCache.cpp \
        core/daemon/src/RecordingMediaHttpRuntime.cpp \
        core/daemon/src/DaemonRuntime.cpp \
        core/daemon/src/DaemonApp.cpp \
        api/rest/src/SearchTimerCreateRequestParser.cpp \
        api/rest/src/SearchTimerUpdateRequestParser.cpp \
        api/rest/src/SearchTimerDeleteRequestParser.cpp \
        api/rest/src/SearchTimerWorkflowValidationRequestParser.cpp

DAEMON_SRC += $(SECURITY_SRC)
DAEMON_SRC += $(AGENT_CONTROL_PLANE_SRC)
DAEMON_SRC += $(METADATA_PLATFORM_SRC)
DAEMON_SRC += $(MANUAL_RECORDING_METADATA_SRC)
DAEMON_SRC += core/recordings/src/ManualRecordingMetadataRepositoryFacade.cpp

# MediaSessionIssuanceService uses crypt_r for salted credential hashes.
LDFLAGS += -lcrypt
