.PHONY: test-ci-fast test-ci-frontend test-ci-packaging test-all test-vdr test-manual-real test-make-inventory

CI_FAST_TESTS := \
	check-vdr-linkage-contracts \
	test-make-inventory \
	test-build-artifact-paths \
	test-suite-bridge-agent-boundary \
	test-suite-bridge-handshake \
	test-suite-bridge-svdrp-transport-boundary \
	test-suite-bridge-svdrp-transport \
	test-suite-bridge-svdrp-artwork-transport \
	test-suite-bridge-svdrp-metadata-transport \
	test-suite-bridge-epg-metadata-resolver \
	test-epg-scraper-metadata-public-json \
	test-epg-scraper-metadata-controller \
	test-epg-scraper-metadata-routes-contract \
	test-suite-bridge-observation-boundary \
	test-suite-bridge-observation-service \
	test-suite-bridge-observation-worker \
	test-suite-bridge-embedded-runtime-boundary \
	test-suite-bridge-embedded-runtime \
	test-suite-bridge-daemon-runtime-wiring \
	test-recording-native-metadata-contracts \
	test-sb10d-live-acceptance-contract \
	test-live-remote \
	test-fast \
	test-api-router \
	test-restful-api-vdr-timer-action-executor \
	test-search-timer-preview-result-json-serializer \
	test-search-timer-preview-service \
	test-search-timer-preview-epg-cache \
	test-vdr-snapshot-read-service-searchtimer-preview-epg-cache \
	test-api-router-searchtimer-preview-epg-cache \
	test-runtime-config \
	test-epg-event-repository \
	test-suite-bridge-epg-artwork-resolver \
	test-epg-artwork-repository \
	test-epg-artwork-enrichment-service \
	test-epg-artwork-controller \
	test-epg-artwork-public-json-serializer \
	test-epg-cache-artwork-json \
	test-epg-cache-service \
	test-epg-cache-controller \
	test-api-router-epg-cache-routes \
	test-vdr-snapshot-builder-startup-snapshot \
	test-search-timer-preview-epg-cache-refresh-service \
	test-search-timer-preview-epg-cache-refresh-controller \
	test-search-timer-preview-epg-cache-stale-guard \
	test-search-timer-preview-epg-cache-change-invalidator \
	test-snapshot-change-feed-preview-epg-cache-invalidation \
	test-api-router-searchtimer-preview-epg-cache-refresh-route \
	test-api-router-searchtimer-preview-refresh-then-preview \
	test-daemon-runtime-modularity \
	test-daemon-runtime-shutdown-resets \
	test-http-listener-bind-failure-handling \
	test-http-listener-partial-request-timeout \
	test-real-vdr-acceptance-manifest \
	test-phase62-runtime-acceptance-harness \
	test-phase-map-coverage \
	test-github-update-safety-handoff \
	test-recording-mutation-safety-policy \
	test-restfulapi-recording-trash-contract \
	test-systemd-unit-contract

VDR_TESTS := \
	check-vdr-linkage-contracts \
	test-suite-bridge-agent-boundary \
	test-suite-bridge-handshake \
	test-suite-bridge-svdrp-transport-boundary \
	test-suite-bridge-svdrp-transport \
	test-suite-bridge-svdrp-artwork-transport \
	test-suite-bridge-svdrp-metadata-transport \
	test-suite-bridge-epg-metadata-resolver \
	test-epg-scraper-metadata-public-json \
	test-epg-scraper-metadata-controller \
	test-epg-scraper-metadata-routes-contract \
	test-suite-bridge-observation-boundary \
	test-suite-bridge-observation-service \
	test-suite-bridge-observation-worker \
	test-suite-bridge-embedded-runtime-boundary \
	test-suite-bridge-embedded-runtime \
	test-suite-bridge-daemon-runtime-wiring \
	test-recording-native-metadata-contracts \
	test-sb10d-live-acceptance-contract \
	test-live-remote \
	test-backend-node \
	test-backend-registry \
	test-backend-registry-service \
	test-backend-registry-json-serializer \
	test-vdr-config \
	test-external-vdr-adapter \
	test-vdr-adapter-factory \
	test-vdr-service \
	test-vdr-overview-service \
	test-vdr-overview-json-serializer \
	test-vdr-snapshot-builder \
	test-polling-service \
	test-vdr-change-state \
	test-vdr-change-event \
	test-change-detection-service \
	test-snapshot-refresh-decision-service \
	test-snapshot-refresh-planner \
	test-snapshot-update-plan \
	test-snapshot-cache \
	test-snapshot-cache-service \
	test-snapshot-change-feed \
	test-snapshot-change-feed-json-serializer \
	test-snapshot-access-service \
	test-mock-vdr-adapter \
	test-json-string-decoder \
	test-restful-api-status-mapper \
	test-restful-api-event-mapper \
	test-restful-api-channel-mapper \
	test-restful-api-recording-mapper \
	test-vdr-recording-cache-repository \
	test-vdr-recording-query-service-cache \
	test-vdr-recording-folder-controller \
	test-restful-api-timer-mapper \
	test-vdr-timer-operation-request \
	test-vdr-timer-action-result \
	test-vdr-timer-action-result-json-serializer \
	test-vdr-timer-action-executor-interface \
	test-mock-vdr-timer-action-executor \
	test-vdr-timer-action-service \
	test-restful-api-vdr-timer-action-request-builder \
	test-restful-api-vdr-timer-action-executor \
	test-vdr-timer-action-request-parser \
	test-vdr-timer-action-controller \
	test-vdr-timer-action-executor-adapter-registry \
	test-restful-api-vdr-timer-action-executor-adapter \
	test-vdr-timer-action-execution-service \
	test-restful-api-vdr-adapter \
	test-restful-api-change-state-adapter \
	test-person-query-matcher \
	test-person-query-result-json-serializer \
	test-person-search-service \
	test-recording-person-search-result \
	test-recording-person-search-service \
	test-recording-person-search-result-json-serializer \
	test-recording-person-search-controller \
	test-person-query-controller \
	test-genre-classification \
	test-genre-resolver \
	test-genre-resolution-json-serializer \
	test-canonical-genre-registry \
	test-genre-localization \
	test-epg-search-request \
	test-epgsearch-matcher \
	test-epg-search-result \
	test-search-timer \
	test-search-timer-preview-epg-cache \
	test-vdr-snapshot-read-service-searchtimer-preview-epg-cache \
	test-runtime-config \
	test-epg-event-repository \
	test-suite-bridge-epg-artwork-resolver \
	test-epg-artwork-repository \
	test-epg-artwork-enrichment-service \
	test-epg-artwork-controller \
	test-epg-artwork-public-json-serializer \
	test-epg-cache-artwork-json \
	test-epg-cache-service \
	test-epg-cache-controller \
	test-api-router-epg-cache-routes \
	test-vdr-snapshot-builder-startup-snapshot \
	test-search-timer-preview-epg-cache-refresh-service \
	test-search-timer-preview-epg-cache-refresh-controller \
	test-search-timer-preview-epg-cache-stale-guard \
	test-search-timer-preview-epg-cache-change-invalidator \
	test-snapshot-change-feed-preview-epg-cache-invalidation \
	test-api-router-searchtimer-preview-epg-cache-refresh-route \
	test-api-router-searchtimer-preview-refresh-then-preview \
	test-search-timer-discovery \
	test-search-timer-discovery-service \
	test-search-timer-discovery-static-provider \
	test-restfulapi-search-timer-discovery-provider-contract \
	test-searchtimer-discovery-runtime-wiring \
	test-daemon-runtime-modularity \
	test-daemon-runtime-shutdown-resets \
	test-http-listener-bind-failure-handling \
	test-http-listener-partial-request-timeout \
	test-real-vdr-acceptance-manifest \
	test-github-update-safety-handoff \
	test-recording-mutation-safety-policy \
	test-search-timer-automation-evaluation-plan \
	test-search-timer-automation-match-candidate \
	test-search-timer-automation-duplicate-detection \
	test-search-timer-automation-candidate-timer-proposal \
	test-search-timer-automation-dry-run-result-json-serializer \
	test-search-timer-automation-read-only-service \
	test-search-timer-automation-preview-controller \
	test-search-timer-automation-daemon-scheduling-plan \
	test-search-timer-automation-safety-review \
	test-restful-api-search-timer-command-executor \
	test-search-timer-runtime-mutation-policy-executor \
	test-search-timer-create-request-parser \
	test-search-timer-discovery-json-serializer \
	test-search-timer-discovery-controller \
	test-search-timer-workflow-execution-result-json-serializer \
	test-search-timer-workflow-backend-readback-verification-result \
	test-search-timer-workflow-create-readback-verification-service \
	test-search-timer-workflow-update-readback-verification-service \
	test-search-timer-workflow-delete-absence-verification-service \
	test-search-timer-workflow-command-dispatch-service \
	test-search-timer-workflow-end-to-end-verified-execution \
	test-search-timer-workflow-real-execution-policy \
	test-search-timer-workflow-real-execution-enablement-switch \
	test-search-timer-workflow-backend-write-allowlist \
	test-search-timer-workflow-backend-write-permission-gate \
	test-search-timer-workflow-production-policy-gate \
	test-search-timer-workflow-production-executor-hardening-plan \
	test-search-timer-workflow-production-executor-hardening-plan-json-serializer \
	test-search-timer-workflow-real-execution-readiness-review \
	test-search-timer-workflow-real-execution-readiness-review-json-serializer \
	test-search-timer-workflow-guarded-executor-invocation \
	test-search-timer-workflow-executor-invocation-kill-switch \
	test-search-timer-workflow-controlled-test-executor-invocation \
	test-search-timer-workflow-controlled-invocation-audit-trail \
	test-search-timer-workflow-executor-result-mapper \
	test-search-timer-workflow-command-request-mapper \
	test-search-timer-workflow-execution-service \
	test-search-timer-workflow-execution-plan-json-serializer \
	test-search-timer-workflow-planning-service \
	test-search-timer-workflow-execution-plan \
	test-search-timer-workflow-validation-request-parser \
	test-search-timer-workflow-validation-result-json-serializer \
	test-search-timer-workflow-validation-service \
	test-search-timer-workflow-request \
	test-search-timer-query \
	test-search-timer-result \
	test-search-timer-service-interface \
	test-epg-person-search-result \
	test-epg-search-result-json-serializer \
	test-epgsearch-service \
	test-vdr-domain-objects

CI_FRONTEND_TESTS := \
	test-frontend-contracts

CI_PACKAGING_TESTS := \
	test-systemd-unit-contract \
	test-install-staging

EXTENDED_LOCAL_TESTS := \
	test-architecture \
	test-backend-registry-capability-resolver \
	test-backend-runtime-context \
	test-recordings2-install-staging \
	test-content-rating \
	test-content-rating-controller \
	test-content-rating-resolution-json-serializer \
	test-content-rating-resolver \
	test-docs \
	test-epgsearch-matcher \
	test-epgsearch-native-fuzzy-capability-freshness-policy \
	test-epgsearch-native-fuzzy-capability-restore-service \
	test-epgsearch-native-fuzzy-startup-restore-diagnostics \
	test-epgsearch-native-fuzzy-startup-restore-service \
	test-epgsearch-native-fuzzy-startup-restore-validation \
	test-epgsearch-query \
	test-epgsearch-request-mapper \
	test-epgsearch-result-json-serializer \
	test-epgsearch-service \
	test-person \
	test-person-controller \
	test-person-query \
	test-person-resolution-json-serializer \
	test-person-resolver \
	test-phase \
	test-restful-api-search-timer-adapter \
	test-restful-api-search-timer-mapper \
	test-restful-api-timer-conflict-mapper \
	test-restful-api-vdr-adapter-timer-conflicts \
	test-restfulapi-delete-live-error-contract \
	test-restfulapi-executor-preserves-http-error-status \
	test-restfulapi-rename-live-error-contract \
	test-restfulapi-search-timer-command-executor \
	test-search-timer-controller \
	test-search-timer-create-result-json-serializer \
	test-search-timer-create-service \
	test-search-timer-delete-request-parser \
	test-search-timer-delete-result-json-serializer \
	test-search-timer-delete-service \
	test-search-timer-result-json-serializer \
	test-search-timer-service \
	test-search-timer-update-request-parser \
	test-search-timer-update-result-json-serializer \
	test-search-timer-update-service \
	test-vdr-channel-move-controller \
	test-vdr-snapshot-read-json-serializer \
	test-vdr-timer-conflict-json-serializer \
	test-vdr-timer-conflicts

MANUAL_REAL_TESTS := \
	real-vdr-regression \
	test-real-restfulapi-integration \
	test-real-snapshot-builder \
	test-real-change-state \
	test-real-polling-initial-snapshot \
	test-real-polling-stability \
	test-suite-bridge-svdrp-transport-live \
	test-real-suite-bridge-embedded-runtime-live

test-ci-fast: $(CI_FAST_TESTS)

test-vdr: $(VDR_TESTS)

test-ci-frontend: $(CI_FRONTEND_TESTS)

test-ci-packaging: $(CI_PACKAGING_TESTS)

test-all: $(EXTENDED_LOCAL_TESTS) test test-vdr test-ci-frontend test-ci-packaging test-make-inventory

test-manual-real: $(MANUAL_REAL_TESTS)

test-make-inventory:
	python3 tools/audit_make_test_inventory.py --check
