VDR_SRC := \
        core/vdr/src/VdrConfig.cpp \
        core/vdr/src/BackendRegistry.cpp \
        core/vdr/src/BackendRegistryService.cpp \
        core/vdr/src/BackendRegistryJsonSerializer.cpp \
        core/vdr/src/CapabilityStateJsonSerializer.cpp \
        core/vdr/src/CapabilityReportJsonSerializer.cpp \
        core/vdr/src/CapabilityReportService.cpp \
        core/vdr/src/ExternalVdrAdapter.cpp \
        core/vdr/src/MockVdrAdapter.cpp \
        core/vdr/src/VdrService.cpp \
        core/vdr/src/VdrRecordingQueryService.cpp \
        core/vdr/src/VdrRecordingQueryMatcher.cpp \
        core/vdr/src/VdrRecordingQueryResultJsonSerializer.cpp \
        core/vdr/src/EpgQueryService.cpp \
        core/vdr/src/EpgSearchMatcher.cpp \
        core/vdr/src/EpgSearchResultJsonSerializer.cpp \
        core/vdr/src/EpgSearchRequestMapper.cpp \
        core/vdr/src/EpgSearchService.cpp \
        core/vdr/src/RestfulApiChannelMapper.cpp \
        core/vdr/src/RestfulApiRecordingMapper.cpp \
        core/vdr/src/RestfulApiTimerMapper.cpp \
        core/vdr/src/RestfulApiEventMapper.cpp \
        core/vdr/src/RestfulApiStatusMapper.cpp \
        core/vdr/src/RestfulApiVdrAdapter.cpp \
        core/vdr/src/SearchTimerCreateService.cpp \
        core/vdr/src/SearchTimerCreateResultJsonSerializer.cpp \
        core/vdr/src/SearchTimerUpdateService.cpp \
        core/vdr/src/SearchTimerUpdateResultJsonSerializer.cpp \
        core/vdr/src/SearchTimerDeleteService.cpp \
        core/vdr/src/SearchTimerDeleteResultJsonSerializer.cpp \
        core/vdr/src/SearchTimerPreviewService.cpp \
        core/vdr/src/SearchTimerPreviewResultJsonSerializer.cpp \
        core/vdr/src/SearchTimerWorkflowValidationService.cpp \
        core/vdr/src/SearchTimerWorkflowPlanningService.cpp \
        core/vdr/src/SearchTimerWorkflowExecutionService.cpp \
        core/vdr/src/SearchTimerWorkflowExecutionResultJsonSerializer.cpp \
        core/vdr/src/SearchTimerWorkflowExecutionPlanJsonSerializer.cpp \
        core/vdr/src/SearchTimerWorkflowValidationResultJsonSerializer.cpp \
        core/vdr/src/RestfulApiSearchTimerCommandExecutor.cpp \
        core/vdr/src/VdrOverviewService.cpp \
        core/vdr/src/VdrOverviewJsonSerializer.cpp \
        core/vdr/src/VdrSnapshotBuilder.cpp \
        core/vdr/src/PollingService.cpp \
        core/vdr/src/VdrChangeState.cpp \
        core/vdr/src/VdrChangeEvent.cpp \
        core/vdr/src/ChangeDetectionService.cpp \
        core/vdr/src/SnapshotRefreshDecision.cpp \
        core/vdr/src/SnapshotRefreshDecisionService.cpp \
        core/vdr/src/SnapshotUpdatePlan.cpp \
        core/vdr/src/SnapshotRefreshPlanner.cpp \
        core/vdr/src/SnapshotCache.cpp \
        core/vdr/src/SnapshotCacheService.cpp \
        core/vdr/src/SnapshotAccessService.cpp \
        core/vdr/src/VdrSnapshotReadService.cpp \
        core/vdr/src/VdrSnapshotReadJsonSerializer.cpp \
        core/vdr/src/SnapshotChangeFeedEntry.cpp \
        core/vdr/src/SnapshotChangeFeed.cpp \
        core/vdr/src/SnapshotChangeFeedService.cpp \
        core/vdr/src/SnapshotChangeFeedJsonSerializer.cpp \
        core/vdr/src/LiveUpdateEvent.cpp \
        core/vdr/src/LiveUpdateEventJsonSerializer.cpp \
        core/vdr/src/TestLiveTransport.cpp \
        core/vdr/src/LiveTransportService.cpp \
        core/vdr/src/LiveTransportFactory.cpp \
        core/vdr/src/SseLiveTransport.cpp \
        core/vdr/src/BackendPollingCoordinator.cpp \
        core/vdr/src/VdrAdapterFactory.cpp
