VDR_SRC := \
        core/vdr/src/VdrConfig.cpp \
        core/vdr/src/BackendRegistry.cpp \
        core/vdr/src/BackendRegistryService.cpp \
        core/vdr/src/BackendRegistryJsonSerializer.cpp \
        core/vdr/src/ExternalVdrAdapter.cpp \
        core/vdr/src/MockVdrAdapter.cpp \
        core/vdr/src/VdrService.cpp \
        core/vdr/src/RestfulApiChannelMapper.cpp \
        core/vdr/src/RestfulApiRecordingMapper.cpp \
        core/vdr/src/RestfulApiTimerMapper.cpp \
        core/vdr/src/RestfulApiEventMapper.cpp \
        core/vdr/src/RestfulApiStatusMapper.cpp \
        core/vdr/src/RestfulApiVdrAdapter.cpp \
        core/vdr/src/VdrOverviewService.cpp \
        core/vdr/src/VdrOverviewJsonSerializer.cpp \
        core/vdr/src/VdrSnapshotBuilder.cpp \
        core/vdr/src/PollingService.cpp \
        core/vdr/src/VdrChangeState.cpp \
        core/vdr/src/VdrChangeEvent.cpp \
        core/vdr/src/ChangeDetectionService.cpp \
        core/vdr/src/SnapshotRefreshDecision.cpp \
        core/vdr/src/SnapshotRefreshDecisionService.cpp \
        core/vdr/src/SnapshotUpdatePlan.cpp \
        core/vdr/src/SnapshotRefreshPlanner.cpp \
        core/vdr/src/SnapshotCache.cpp \
        core/vdr/src/SnapshotCacheService.cpp \
        core/vdr/src/SnapshotAccessService.cpp \
        core/vdr/src/VdrSnapshotReadService.cpp \
        core/vdr/src/VdrSnapshotReadJsonSerializer.cpp \
        core/vdr/src/SnapshotChangeFeedEntry.cpp \
        core/vdr/src/SnapshotChangeFeed.cpp \
        core/vdr/src/SnapshotChangeFeedService.cpp \
        core/vdr/src/SnapshotChangeFeedJsonSerializer.cpp \
        core/vdr/src/BackendPollingCoordinator.cpp \
        core/vdr/src/VdrAdapterFactory.cpp
