#!/usr/bin/env python3
"""Build the browser-served EPG runtime in deterministic execution order.

The HTTP server appends the installed epg-cache.js to channel-logos.js, which is
loaded before app.js. Legacy epg-cache.js therefore must not execute until the
DOM is ready and app.js has established its global runtime functions.
"""

from __future__ import annotations

import argparse
from pathlib import Path


LEGACY_SOURCE = Path("web/frontend/epg-cache.js")
DAY_PROGRAM_SOURCE = Path("web/frontend/channel-day-program.js")
COMPAT_SOURCE = Path("web/frontend/channel-day-program-compat.js")


def indent_source(source: str, spaces: int = 4) -> str:
    prefix = " " * spaces
    return "\n".join(prefix + line if line else "" for line in source.splitlines())


def read_source(root: Path, relative_path: Path) -> str:
    path = root / relative_path
    if not path.is_file():
        raise FileNotFoundError(f"required frontend source not found: {path}")
    return path.read_text(encoding="utf-8").rstrip() + "\n"


def build_runtime(root: Path) -> str:
    legacy = read_source(root, LEGACY_SOURCE)
    day_program = read_source(root, DAY_PROGRAM_SOURCE)
    compatibility = read_source(root, COMPAT_SOURCE)

    deferred_legacy = """// Generated by tools/build_frontend_epg_runtime.py.
// The legacy EPG cache runtime is intentionally deferred until app.js exists.
(function(global) {
  'use strict';

  function startVdrSuiteLegacyEpgRuntime() {
%s
  }

  function bootVdrSuiteLegacyEpgRuntime() {
    if (global.__vdrSuiteLegacyEpgRuntimeStarted === true) return;
    global.__vdrSuiteLegacyEpgRuntimeStarted = true;
    startVdrSuiteLegacyEpgRuntime();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', bootVdrSuiteLegacyEpgRuntime, {once: true});
  } else {
    bootVdrSuiteLegacyEpgRuntime();
  }
})(window);
""" % indent_source(legacy, 4)

    return (
        deferred_legacy.rstrip()
        + "\n\n"
        + day_program.rstrip()
        + "\n\n"
        + compatibility.rstrip()
        + "\n"
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build the deferred VDR-Suite EPG browser runtime bundle."
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path.cwd(),
        help="Repository root (default: current working directory).",
    )
    parser.add_argument(
        "--output",
        type=Path,
        required=True,
        help="Output JavaScript file.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = args.root.resolve()
    output = args.output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_runtime(root), encoding="utf-8")
    print(f"frontend EPG runtime built: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
