#!/usr/bin/env python3
"""Calibrate VDR-Suite software video-transcode workloads for auto policy."""

from __future__ import annotations

import argparse
import os
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile
from typing import Dict

PRESETS = ("superfast", "veryfast", "faster", "fast")
QUALITY_ORDER = ("fast", "faster", "veryfast", "superfast")
MINIMUM_REALTIME_SPEED = 1.25
SPEED_RE = re.compile(r"speed=\s*([0-9]+(?:\.[0-9]+)?)x")

WORKLOADS = {
    "standard": {
        "source": "testsrc2=size=1920x1080:rate=25",
        "filter": "scale=1920:1080",
    },
    "deinterlace": {
        "source": "testsrc2=size=1920x1080:rate=50",
        "filter": (
            "tinterlace=mode=interleave_top,"
            "bwdif=mode=send_frame:parity=auto:deint=all,"
            "scale=1920:1080"
        ),
    },
    "uhd-source": {
        "source": "testsrc2=size=3840x2160:rate=25",
        "filter": "scale=1920:1080",
    },
}


def benchmark(ffmpeg: str, workload: str, preset: str, seconds: int) -> float:
    spec = WORKLOADS[workload]
    command = [
        ffmpeg,
        "-hide_banner",
        "-stats",
        "-stats_period",
        "0.5",
        "-v",
        "warning",
        "-f",
        "lavfi",
        "-i",
        spec["source"],
        "-t",
        str(seconds),
        "-an",
        "-c:v",
        "libx264",
        "-preset",
        preset,
        "-crf",
        "20",
        "-vf",
        spec["filter"],
        "-pix_fmt",
        "yuv420p",
        "-f",
        "null",
        "-",
    ]
    completed = subprocess.run(
        command,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.PIPE,
        text=True,
        timeout=max(60, seconds * 20),
        check=False,
    )
    if completed.returncode != 0:
        tail = "\n".join(completed.stderr.splitlines()[-12:])
        raise RuntimeError(
            f"ffmpeg benchmark failed for {workload}/{preset}:\n{tail}"
        )
    speeds = [float(match.group(1)) for match in SPEED_RE.finditer(completed.stderr)]
    if not speeds:
        raise RuntimeError(
            f"ffmpeg produced no speed metric for {workload}/{preset}"
        )
    return speeds[-1]


def recommended_preset(samples: Dict[str, float]) -> str:
    for preset in QUALITY_ORDER:
        if samples.get(preset, 0.0) >= MINIMUM_REALTIME_SPEED:
            return preset
    return "superfast"


def write_profile(path: pathlib.Path, results: Dict[str, Dict[str, float]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by vdr-suite-media-calibrate.",
        "# Values are maximum measured software-transcode speed multipliers.",
        "version=1",
    ]
    for workload in WORKLOADS:
        for preset in PRESETS:
            lines.append(f"{workload}.{preset}={results[workload][preset]:.3f}")
    lines.append("")

    handle = tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        dir=str(path.parent),
        prefix=f".{path.name}.",
        delete=False,
    )
    temporary = pathlib.Path(handle.name)
    try:
        with handle:
            handle.write("\n".join(lines))
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temporary, 0o644)
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Benchmark representative VDR-Suite x264 workloads and write the "
            "server performance profile used by VDR_SUITE_MEDIA_X264_PRESET=auto."
        )
    )
    parser.add_argument(
        "--output",
        default="/var/lib/vdr-suite/media-transcode-performance.conf",
        help="performance profile path",
    )
    parser.add_argument(
        "--seconds",
        type=int,
        default=6,
        help="media seconds per benchmark (default: 6)",
    )
    args = parser.parse_args()

    if args.seconds < 3 or args.seconds > 30:
        parser.error("--seconds must be between 3 and 30")

    ffmpeg = shutil.which("ffmpeg")
    if not ffmpeg:
        print("vdr-suite-media-calibrate: ffmpeg not found", file=sys.stderr)
        return 2

    results: Dict[str, Dict[str, float]] = {}
    try:
        for workload in WORKLOADS:
            results[workload] = {}
            print(f"[{workload}]")
            for preset in PRESETS:
                speed = benchmark(ffmpeg, workload, preset, args.seconds)
                results[workload][preset] = speed
                verdict = "PASS" if speed >= MINIMUM_REALTIME_SPEED else "slow"
                print(f"  {preset:9s} {speed:5.3f}x  {verdict}")
            print(
                "  auto -> "
                f"{recommended_preset(results[workload])} "
                f"(minimum {MINIMUM_REALTIME_SPEED:.2f}x)"
            )
    except (RuntimeError, subprocess.TimeoutExpired) as error:
        print(f"vdr-suite-media-calibrate: {error}", file=sys.stderr)
        return 3

    output = pathlib.Path(args.output)
    try:
        write_profile(output, results)
    except OSError as error:
        print(
            f"vdr-suite-media-calibrate: cannot write {output}: {error}",
            file=sys.stderr,
        )
        if str(output).startswith("/var/lib/"):
            print("Run the calibrator with sudo for the default system path.", file=sys.stderr)
        return 4

    print(f"Wrote {output}")
    print("Restart vdr-suite-daemon to load the new auto policy.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
