'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const clientSource=fs.readFileSync(path.join(__dirname,'..','api','live-remote-client-api.js'),'utf8');
const source=fs.readFileSync(path.join(__dirname,'..','modules','remote.js'),'utf8');
const remoteAssetPath=path.join(__dirname,'..','assets','vdr-remote-photorealistic.jpg');
const remoteSvgPath=path.join(__dirname,'..','assets','vdr-remote-photorealistic.svg');
const remoteAsset=fs.readFileSync(remoteAssetPath),remoteAssetText=remoteAsset.toString('latin1');
function jpegDimensions(data){const sof=new Set([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf]);let p=2;while(p+9<=data.length){if(data[p]!==0xff){p++;continue}while(p<data.length&&data[p]===0xff)p++;if(p>=data.length)break;const marker=data[p++];if(marker===0x01||marker===0xd8||marker===0xd9||(marker>=0xd0&&marker<=0xd7))continue;if(p+2>data.length)break;const length=data.readUInt16BE(p);if(length<2||p+length>data.length)break;if(sof.has(marker))return{width:data.readUInt16BE(p+5),height:data.readUInt16BE(p+3)};p+=length}throw new Error('JPEG dimensions not found')}
assert(!source.includes('/remote/seq'));assert(!source.includes('/remote/kbd'));assert(!source.includes('/osd'));assert(!source.includes('restfulapi'));assert(!source.includes('/api/vdr/remote/actions'));assert(!source.includes('/api/vdr/live/overlay'));assert(clientSource.includes("'/api/vdr/remote/actions'"));assert(clientSource.includes("'/api/vdr/live/overlay'"));assert(clientSource.includes("'/api/vdr/live'"));
assert(source.includes("P='/channel-logos/vdr-suite-brand/vdr-remote-photorealistic.jpg'"));assert(!source.includes('vdr-remote-photorealistic.svg'));assert(!source.includes('data:image/'));assert(!source.includes('<image'));assert(source.includes("el('section','rst')"));assert(source.includes("el('img','rpi')"));assert(source.includes("el('button','rpk')"));assert(source.includes("s.setAttribute('aria-label','Fotorealistische VDR-Fernbedienung')"));assert(source.includes("z.textContent='Fotorealistisch · scrollbar'"));
assert.strictEqual(remoteAsset[0],0xff);assert.strictEqual(remoteAsset[1],0xd8);assert.strictEqual(remoteAsset[remoteAsset.length-2],0xff);assert.strictEqual(remoteAsset[remoteAsset.length-1],0xd9);assert.deepStrictEqual(jpegDimensions(remoteAsset),{width:360,height:1220});assert(!remoteAssetText.includes('<image'));assert(!remoteAssetText.includes('data:image/'));assert(!fs.existsSync(remoteSvgPath));
assert(source.includes('let d=null,n=0,e=null,q=0,busy=false'));assert(source.includes("x.classList.add('down')"));assert(source.includes("x.classList.remove('down')"));assert(source.includes("x.classList.add('send')"));assert(source.includes("x.classList.remove('send')"));assert(source.includes("x.getAttribute('aria-disabled')==='true'||busy"));assert(!source.includes('lockControls(true)'));assert(!source.includes('button.disabled = locked'));assert(source.includes('.rpk.down::before'));assert(source.includes('.rpk:not(.off):active::before'));assert(source.includes('transform:translateY(2px) scale(.985)'));assert(source.includes('width:min(19rem,72vw)'));assert(!source.includes('width:min(23rem,88vw)'));assert(source.includes('width:min(22rem,88vw)'));assert(source.includes('overflow-y:auto'));assert(source.includes('position:sticky'));assert(!source.includes('.rpk:hover'));assert(!source.includes('.brand-feature-remote:hover'));assert(source.includes('hotspotCount:H.length'));
assert(source.includes("x.classList.add('brand-feature-remote')"));assert(source.includes("x.setAttribute('aria-label','VDR - Fernbedienung öffnen')"));assert(source.includes("el('h2','','VDR - Fernbedienung')"));assert(source.includes("v.setAttribute('aria-label','VDR - Fernbedienung')"));assert(source.includes("t.textContent='VDR - Fernbedienung'"));
const serverPaths=fs.readFileSync(path.join(__dirname,'..','..','..','core','http','src','TestHttpServerPaths.inc'),'utf8'),liveRemoteMake=fs.readFileSync(path.join(__dirname,'..','..','..','mk','live-remote.mk'),'utf8');assert(serverPaths.includes('{"/frontend/app.js", "app.js", "application/javascript; charset=utf-8", "modules/remote.js"}'));assert(serverPaths.includes('{"/frontend/api/client-api.js", "api/client-api.js", "application/javascript; charset=utf-8", "api/live-remote-client-api.js"}'));assert(liveRemoteMake.includes('web/frontend/modules/remote.js'));assert(liveRemoteMake.includes('web/frontend/api/live-remote-client-api.js'));assert(liveRemoteMake.includes('web/frontend/assets/vdr-remote-photorealistic.jpg'));assert(!liveRemoteMake.includes('vdr-remote-photorealistic.svg'));
const document={head:{appendChild:function(){}},body:{append:function(){}},createElement:function(tag){return{tagName:tag.toUpperCase(),dataset:{},style:{},classList:{add:function(){},remove:function(){},toggle:function(){}},setAttribute:function(){},getAttribute:function(){return null},removeAttribute:function(){},appendChild:function(){},append:function(){},addEventListener:function(){},querySelector:function(){return null},querySelectorAll:function(){return[]}}},querySelector:function(){return null},querySelectorAll:function(){return[]},getElementById:function(){return null},addEventListener:function(){}};
const requests=[],baseApi=Object.freeze({requestJson:function(url,options){requests.push({url:url,options:options});return Promise.resolve({success:true})},fetchClientBackends:function(){return Promise.resolve({backends:[]})}}),context={window:null,document:document,console:console,Date:Date,JSON:JSON,Object:Object,Promise:Promise,Set:Set,URLSearchParams:URLSearchParams,setTimeout:setTimeout,clearTimeout:clearTimeout,VdrSuiteClientApi:baseApi};context.window=context;vm.createContext(context);vm.runInContext(clientSource,context);vm.runInContext(source,context);
assert(context.VdrSuiteRemote);assert.strictEqual(context.VdrSuiteRemote.remoteImagePath,'/channel-logos/vdr-suite-brand/vdr-remote-photorealistic.jpg');assert.strictEqual(context.VdrSuiteRemote.hotspotCount,35);assert.deepStrictEqual(Array.from(context.VdrSuiteRemote.actions),['up','down','left','right','ok','back','menu','info','red','green','yellow','blue','zero','one','two','three','four','five','six','seven','eight','nine','channelUp','channelDown','volumeUp','volumeDown','mute','play','pause','stop','record','fastForward','rewind','next','previous','switchChannel']);assert.strictEqual(typeof context.VdrSuiteClientApi.fetchClientRemoteAction,'function');assert.strictEqual(typeof context.VdrSuiteClientApi.fetchClientLiveOverlay,'function');assert.strictEqual(context.VdrSuiteRemote.canControlBackend({enabled:true,online:true,frontendSelector:{canWrite:false},capabilities:{remoteControl:true}}),false);assert.strictEqual(context.VdrSuiteRemote.canControlBackend({enabled:true,online:true,frontendSelector:{canWrite:true},capabilities:{remoteControl:true}}),true);
context.VdrSuiteClientApi.fetchClientRemoteAction({payload:{backendId:'default',operationId:'remote-1',action:'ok'}});context.VdrSuiteClientApi.fetchClientLiveOverlay({backendId:'default'});assert.strictEqual(requests[0].url,'/api/vdr/remote/actions');assert.strictEqual(requests[0].options.method,'POST');assert.strictEqual(requests[1].url,'/api/vdr/live/overlay');console.log('remote frontend contract ok');
